import googleSvg from "@/assets/svg/google.svg";
import githubSvg from "@/assets/svg/github-dark.svg";
import {
  Palette,
  Type,
  Component,
  Clock,
  ArrowLeft,
  Plus,
  Loader2,
  Upload,
  Download,
  Play,
  Eye,
  Film,
  Music,
  Image as ImageIcon,
  Undo,
  Redo,
  PlayCircle,
  Bell,
  Settings,
  Share2,
  ChevronDown,
  MousePointer2,
  Brush,
  Hand,
  Check as CheckIcon,
  ChevronDown as ChevronDownIcon,
  ChevronUp as ChevronUpIcon,
  Lock,
  Unlock,
  ZoomIn,
  ZoomOut,
  Maximize,
  EyeOff,
} from "lucide-react";

export const Google = (props: React.ComponentProps<"img">) => (
  <img src={googleSvg} alt="Google" {...props} />
);

export const Github = (props: React.ComponentProps<"img">) => (
  <img src={githubSvg} alt="GitHub" {...props} />
);

export {
  Palette,
  Type,
  Component,
  Clock,
  ArrowLeft,
  Plus,
  Loader2,
  Upload,
  Download,
  Play,
  Eye,
  Film,
  Music,
  ImageIcon,
  Undo,
  Redo,
  PlayCircle,
  Bell,
  Settings,
  Share2,
  ChevronDown,
  MousePointer2,
  Brush,
  Hand,
  CheckIcon,
  ChevronDownIcon,
  ChevronUpIcon,
  Lock,
  Unlock,
  ZoomIn,
  ZoomOut,
  Maximize,
  EyeOff,
};
